### ISSUE TITLE
🐛 Bug Bash!

### ISSUE THREAD

**Issue by drwpow** [withastro/astro#245]
Results of our May 25th Bug Bash session, rolled into one issue:

- [x] BUG: No src directory or no src/pages directory = error (solution: change `astroRoot` to `pages` or something that points to `src/pages` directory?)
- [x] If `import Foo from '../components/Foo.astro';` doesn’t exist, an error shows, but it’s missing the full filepath, and the error stack is noisy (just a simple `XXX not found` will suffice) (added test #251) [@drwpow]
- [x] https://github.com/snowpackjs/astro/issues/243
- [ ] Generated slug (`hello-content`) is based on source text, not final output (`<Markdown># Hello {content}</Markdown>`)
- [ ] Markdown inside of Svelte inside of Markdown doesn't work
- [x] slow startup on first start (improved even more in #253) [@matthewp]
- [x] Frontmatter script comments are broken in Code (uses `#` instead of `//`) (#263) [@natemoo-re]
- [x] `npm init astro` fails on npm v7 (#183) (proposed solution: make `react` dep, not peerDep)
- [x] `npm init astro ./myproject` outputs `Project initialized at ././my-project` (fixed in #242)
- [x] color contrast isn't enough for create-astro (dark mode?) [@drwpow]
- [x] Update starter templates to use `"astro": "latest"` (currently they’re on `^0.10.0`, one version behind) #248 
- [x] Getting Started template showing Times New Roman in Firefox [@drwpow]
- [x] Update `Tour.astro` file to use `<Markdown>` (where it makes sense to) [@matthewp]
- [x] Remove “blank” template, only have Getting Started (and Blog?) [@drwpow]
- [x] In Getting Started template, update `astro.config.mjs` to remove `snowpack` and comment out default options (but keep descriptions) (fixed in #250)
- [x] Code frame is commented out in error (fixed as a side-effect of Prism issues)
- [x] If non-Astro file exists but is empty, 500 page shows weird error ([upstream Snowpack issue](https://github.com/snowpackjs/snowpack/pull/3380))
- [x] Markdown: Code blocks not syntax highlighted in `<Markdown>` component [@matthewp]
- [x] Markdown: Code blocks are not included in `.md` files. [@matthewp]
- [x] Starter template in astro `0.11.0` tree view is messed up (missing `<pre>` tag)
- [x] ~Markdown: If you use code blocks inside `<Markdown>` component, it generates a `<pre>` tag without a scoped class ( `class="astro-*`), making styling it very difficult. But `<code>` within still has scoped class.~ This was fixed already (bug from older Astro version)?
- [x] `import 'emoji-mart/css/emoji-mart.css'`; in an Astro frontmatter silently fails. It should probably error with a "hey, this should be a link tag if you want it on the page" [@drwpow]
- [x] Styling docs: improve/revise? [@drwpow]
